sudo: false
language: node_js
node_js:
  - 11

addons:
  chrome: stable

before_install:
  - cd frontend
  - npm install
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost &

script:
  - cd frontend
  - npm run travis:test
