language: node_js
node_js:
  - 11
dist: trusty
sudo: required
addons:
  chrome: stable
cache: npm
before_install:
  - cd frontend
  - npm install

script:
  - npm run travis:test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "yup-yup"
  env: "YupYup-env"
  bucket_name: "elasticbeanstalk-us-east-2-801924716222"
  bucket_path: "yup-yup"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"