language: node_js
node_js:
  - 11
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - cd frontend
  - npm install

script:
  - npm run travis:test
