language: node_js
node_js:
  - 11
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd frontend
  - npm install
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost &

script:
  - npm run travis:test
